
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

// Remote contract interface
interface InferfaceGameObject {
    function acceptAttack(uint power) external;
}